// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzIiIoEU2lVawLsKLnLm8SRdmfJE8R7mE',
    appId: '1:647856247504:web:4d4ef4301a6429416e44d5',
    messagingSenderId: '647856247504',
    projectId: 'test-juling',
    authDomain: 'test-juling.firebaseapp.com',
    storageBucket: 'test-juling.appspot.com',
    measurementId: 'G-WZCSXM86GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzyTeGMln8OKK3B2T3PKnJ5ZhEcxkG_Cc',
    appId: '1:647856247504:android:e62ce398bc6ff66e6e44d5',
    messagingSenderId: '647856247504',
    projectId: 'test-juling',
    storageBucket: 'test-juling.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-9IhrDg9gjV1Gckd9k6t1ykTWM3FIBnc',
    appId: '1:647856247504:ios:4a3a2a84e96cf7656e44d5',
    messagingSenderId: '647856247504',
    projectId: 'test-juling',
    storageBucket: 'test-juling.appspot.com',
    iosBundleId: 'com.example.julingApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-9IhrDg9gjV1Gckd9k6t1ykTWM3FIBnc',
    appId: '1:647856247504:ios:31c59e65da3cb2a46e44d5',
    messagingSenderId: '647856247504',
    projectId: 'test-juling',
    storageBucket: 'test-juling.appspot.com',
    iosBundleId: 'com.example.julingApps.RunnerTests',
  );
}
